AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cf-events-trigger

  Sample SAM Template for cf-events-trigger

Globals:
  Function:
    Timeout: 3

    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MyEventRule
      EventBusName: default
      Targets:
        - Arn: !GetAtt HelloWorldStateMachine.Arn
          Id: "MyEventRule"
          RoleArn: !GetAtt MyEventRuleIAMRole.Arn
          InputPath: $.detail
      EventPattern:
        source:
          - aws.cloudformation
        detail-type:
          - "CloudFormation Resource Status Change"
        detail:
          status-details:
            status: 
              - "CREATE_COMPLETE"
              - "UPDATE_COMPLETE"
          resource-type:
            - "AWS::Lambda::Function"
          logical-resource-id: 
            - "HelloWorldFunction"
          # physical-resource-id:
          #   - !GetAtt HelloWorldFunction.Arn
  
  MyEventRuleIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub events.amazonaws.com
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: PutEventsDestinationBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource:
                  - !GetAtt HelloWorldStateMachine.Arn

  HelloWorldStateMachine:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: hello-world.asl.json

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'